# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.0.6

    working_directory: ~/repo

    steps:
      # There are ways to cache things on order to skip the whole time waiting for npm install
      - run: npm install

      # run tests!
      - run: npm test
